// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-hAtxpjciMFpWQaOlFQMrD6PskX0FpZM',
    appId: '1:335367935384:android:7a6aeac4eac2ce51fd47ed',
    messagingSenderId: '335367935384',
    projectId: 'earthquakdb',
    databaseURL: 'https://earthquakdb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'earthquakdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPqS-Xc-CMLXcioL_ChCyJ4snJp6V4n04',
    appId: '1:335367935384:ios:c2405b0aa22f0d2bfd47ed',
    messagingSenderId: '335367935384',
    projectId: 'earthquakdb',
    databaseURL: 'https://earthquakdb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'earthquakdb.firebasestorage.app',
    iosBundleId: 'com.beniyiyim.benIyiyim',
  );
}
